{% set name = "scikit-learn-intelex" %}
{% set version = "2021.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/scikit-learn-intelex/archive/{{ version }}.tar.gz
  sha256: b463068f493305891f83056f8e46a3b38e8596a3c9251a3e2ff428720b852f63

build:
  number: 0
  script: {{ PYTHON }} setup_sklearnex.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - daal4py ==2021.2.2
    - scikit-learn >=0.21

test:
  requires:
    - pandas
    - pytest
  source_files:
    - sklearnex/tests
  commands:
    - python -c "import sklearnex"
    - python -c "from sklearnex import patch_sklearn; patch_sklearn()"
    - python -m pytest sklearnex/tests

about:
  home: https://intel.github.io/scikit-learn-intelex
  license: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - doc/third-party-programs-sklearnex.txt
  summary: Intel(R) Extension for Scikit-learn* speeds up scikit-learn beyond by providing drop-in patching. Acceleration is achieved through the use of the Intel(R) oneAPI Data Analytics Library that allows for fast usage of the framework suited for Data Scientists or Machine Learning users.
  description: |
    <strong>LEGAL NOTICE: Use of this software package is subject to the
    software license agreement (as set forth above, in the license section of
    the installed Conda package and/or the README file) and all notices,
    disclaimers or license terms for third party or open source software
    included in or with the software.</strong>
    <br/><br/>
    EULA: <a href="https://opensource.org/licenses/Apache-2.0" target="_blank">Apache-2.0</a>
    <br/><br/>
  dev_url: https://github.com/intel/scikit-learn-intelex
  doc_url: https://intel.github.io/scikit-learn-intelex

extra:
  recipe-maintainers:
    - napetrov
    - PetrovKP
    - SmirnovEgorRu
    - Pahandrovich
