# NB: this recipe should be synced between sklearnex repo and feedstocks

{% set name = "scikit-learn-intelex" %}
{% set buildnumber = 0 %}
# version is set manually in feedstocks and through git tag in repo
{% set version = "2025.8.0" %}

package:
  name: {{ name|lower }}
  # version: {{ environ.get('GIT_DESCRIBE_TAG') }}
  version: {{ version }}

# Reminder: source should point to path for repo or github archive for feedstock
source:
  url: https://github.com/uxlfoundation/scikit-learn-intelex/archive/{{ version }}.tar.gz
  sha256: d74841b7c6b4f2242a5b8f13e6b990e81f23042df5a392e67975d109d18a7ae7
# source:
#   path: ..

build:
  skip: true  # [not (linux64 or win)]
  number: {{ buildnumber }}
  include_recipe: false
  script_env:
    - DPCPPROOT
    - DALROOT
    - NO_DIST=1  # [win]
  ignore_run_exports_from:
    - {{ compiler('dpcpp') }}  # [linux64]

requirements:
  build:
    - make  # [linux]
    - {{ compiler('dpcpp') }}  # [linux64]
    - {{ compiler('cxx') }}
    # conda-forge feedstock specific
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cmake
    - clang-format
    - cython
    - jinja2
    - pybind11
    - numpy
    # dal-devel pinning depends on the recipe location (repo or feedstock)
    # - dal-devel
    - dal-devel =={{ version }}
    - impi-devel  # [not win]
    - mpi * impi  # [not win]
  run:
    - python
    - numpy
    - scikit-learn
    - scikit-learn  <1.6  # [py<=39]
    # dal-devel has run_exports on conda-forge, so no need to add it.
    - mpi * impi  # [not win]

test:
  requires:
    - pyyaml
    - mpi * impi  # [not win]
    # DPC part of sklearnex is optional
    - dpcpp-cpp-rt  # [linux64]
    # TODO: enable data parallel frameworks when they are available on conda-forge
    # - dpctl
    # - dpnp
    # next deps are synced with requirements-test.txt
    - pytest
    - pandas
    - xgboost
    - lightgbm
    - treelite
    - shap
    - catboost
    - array-api-compat
    - array-api-strict
    - array-api-strict <2.4  # [py<312]
  source_files:
    - .ci
    - .pytest-verbosity-args
    - examples
    - tests

about:
  home: https://uxlfoundation.github.io/scikit-learn-intelex
  license: Apache-2.0
  license_file:
    - LICENSE
    - doc/third-party-programs-sklearnex.txt
  summary: Intel(R) Extension for Scikit-learn* is a seamless way to speed up your Scikit-learn application.
  description: |
    Extension for Scikit-learn is a <strong>free software AI accelerator</strong> designed to deliver over
    <strong>10-100X</strong> acceleration to your existing scikit-learn code. The software acceleration is
    achieved with vector instructions, AI hardware-specific memory optimizations, threading, and optimizations.
    <br/><br/>
    With Extension for Scikit-learn, you can:
    <ul>
    <li>Speed up training and inference by up to 100x with equivalent mathematical accuracy</li>
    <li>Benefit from performance improvements across different hardware configurations, including
        <a href="https://uxlfoundation.github.io/scikit-learn-intelex/latest/oneapi-gpu.html" target="_blank">GPUs</a>
        and <a href="https://uxlfoundation.github.io/scikit-learn-intelex/latest/distributed-mode.html" target="_blank">multi-GPU</a>
        configurations
    </li>
    <li>Integrate the extension into your existing Scikit-learn applications without code modifications</li>
    <li>Continue to use the open-source scikit-learn API</li>
    <li>Enable and disable the extension with a couple of lines of code or at the command line</li>
    </ul>
  dev_url: https://github.com/uxlfoundation/scikit-learn-intelex
  doc_url: https://uxlfoundation.github.io/scikit-learn-intelex

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - napetrov
    - Alexsandruss
    - maria-Petrova
    - ethanglaser
